// This file is automatically generated. Do not modify it manually.

package main

import (
	"strings"

	"github.com/mattermost/mattermost-server/v5/model"
)

var manifest *model.Manifest

const manifestStr = `
{
  "id": "com.nilsbrinkmann.icebreaker",
  "name": "Icebreaker Plugin",
  "description": "This plugin creates a bot which asks random questions",
  "homepage_url": "https://github.com/monsdar/mattermost-icebreaker-plugin",
  "support_url": "https://github.com/monsdar/mattermost-icebreaker-plugin/issues",
  "release_notes_url": "https://github.com/monsdar/mattermost-icebreaker-plugin/releases",
  "version": "2.2.1",
  "min_server_version": "5.12.0",
  "server": {
    "executables": {
      "linux-amd64": "server/dist/plugin-linux-amd64",
      "darwin-amd64": "server/dist/plugin-darwin-amd64",
      "windows-amd64": "server/dist/plugin-windows-amd64.exe"
    },
    "executable": ""
  }
}
`

func init() {
	manifest = model.ManifestFromJson(strings.NewReader(manifestStr))
}
